const { transporter, htmlEscape } = require("../../utils/sendVerificationEmail");

const chatBotController = async (req, res) => {
  try {
    const { role, email, phone } = req.body;

    if (!role || !email || !phone) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const htmlTemplate = `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color:#f97316;">🚀 New ChatBot Inquiry</h2>
        <p>A user has submitted their details via the Qualty.ai chatbot:</p>
        <table style="width:100%; border-collapse: collapse; margin-top: 16px;">
          <tr>
            <td style="padding:8px; border:1px solid #ddd; font-weight:bold;">Role</td>
            <td style="padding:8px; border:1px solid #ddd;">${htmlEscape(role)}</td>
          </tr>
          <tr>
            <td style="padding:8px; border:1px solid #ddd; font-weight:bold;">Email</td>
            <td style="padding:8px; border:1px solid #ddd;">${htmlEscape(email)}</td>
          </tr>
          <tr>
            <td style="padding:8px; border:1px solid #ddd; font-weight:bold;">Phone</td>
            <td style="padding:8px; border:1px solid #ddd;">${htmlEscape(phone)}</td>
          </tr>
        </table>
        <p style="margin-top:16px;">Please follow up with this user promptly.</p>
        <hr style="margin:24px 0; border:none; border-top:1px solid #eee;" />
        <p style="font-size:12px; color:#666;">This message was automatically generated by the Qualty.ai chatbot system.</p>
      </div>
    `;

    await transporter.sendMail({
      from: `"Qualty.ai ChatBot"`,
      to: process.env.EMAIL_USER, 
      subject: "New ChatBot Inquiry",
      html: htmlTemplate,
    });

    return res.json({ success: true, message: "ChatBot inquiry sent successfully" });
  } catch (err) {
    console.error("chatBotController error:", err);
    return res.status(500).json({ error: "Failed to process chatbot inquiry" });
  }
};

module.exports = { chatBotController };
